### PR TITLE
#1 - fix node env + some improvements 

### PR DESCRIPTION
**Pull request by b091**
fixes the issue #1

### CODE REVIEW

**Comment by nknapp** [comment]
Hi and thanks for your PR. And wow: Congrats for finding all those things (and thanks for searching and not giving up).
Just a few thoughts:
- **Global dependencies on `thought` and `standard`**: `standard` should be removed completely, because it only lints JavaScript and not TypeScript. I have not added `thought` as dependency because it is rather large. I am using `thought` in almost all of my projects and downloading as local dependency for each one takes a considerable amount of disk-space. Same reason for keeping `standard` global. 
- **Freeze dependency versions**: This is one thing I would not do. At least not yet. Specifying exact version does not freeze the dependencies of the dependencies. I'd rather do a `npm shrinkwrap` before releasing, but I think I would wait until we can publish version 1.0. This should be as soon as it is clear that the library is usable as it is.
- **Adding `dom` to the libs**: I don't think this is necessary. I filed an [issue at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12621) for those errors and they are already corrected in the repo. Just not on npm, I think.

What do you think?

**Comment by nknapp** [comment]
I may have been impatient, but I thought it would be better to publish the non-controversial changes right now rather than later.
I have create commit 79c5cd6361e4dcda0b8078b503e03bd46ade1058 which includes some of your changes and removes `standard` from the repo. 

I'd still like your oppinion for a dependency-freeze in contrast to a shrinkwrap.

**Comment by b091** [comment]
- Global dependencies on thought and standard: as for `thought` for me is ok, but generally speaking it's always better to have packages locally one of the reason is different version of the same package used by different projects (it's something that could be fixed on npm side)
- Freeze dependency versions: as you wish, my experience is to have accidentally not working project in so many different error cases that was then debugged by me and or other developer many times, because someone released a patch for dependency which was braking things. I know it does't freeze deps of deps, but in most cases it secure project for that kind of situations.
- Adding dom to the libs: so i could be added and then removed, or just wait with broken compilation in this project, personally i prefer the first approach

**Comment by nknapp** [comment]
I too agree with local dependencies being better in general. `thought` is the only global one for now and I would prefer it to be local. But I've tried to reduce its package size and it means a lot of work convincing package-maintainers to reduce theirs as well.

Concerning the "dom" libs. The issue is resolved now and the compilation works. I'll re-add the test

**Pull request closed without merging**
