### PR TITLE
Prepare 1.0

### LINKED ISSUE #30: Preferred usage broken
I tried writing an [example for unions](https://github.com/nknapp/graphql-typewriter/blob/docs/examples/unions/usage.ts), but I failed due to the following facts:

* I would like to use `import {schema} from './unions.graphqls'` as import-statement, because
it makes it look like the graphqls-file itself is imported
* There is now more than only interfaces in the resulting typescript-file. That's why, `tsc` will keep the `import`-statement as `require('...')`-statement for NodeJS.
* `require('./unions.graphqls')` does not require the file `./unions.graphqls.js`, but tries to load `./unions.graphqls` as JavaScript, which obviously is not possible.

As a workaround,  `import {schema} from './unions.graphqls.js'` can be used, but that seems kind of weird in a TypeScript-project.

I wonder if it is possible to specify the `defaultResolvers` as interfaces so that no actual code is generated by TypeScript.

### PR DESCRIPTION
**Pull request by nknapp**
- Target-Files are not generated as "name.graphql.types.ts" in order to allow an `import from "name.graphql.types"`. 
- I have also regenerated the documentation.

The first commit changes the package.json such that the coverage tests can also be executed independently locally, without TravisCI. I have added "istanbul", "remap-istanbul" and "thought" to the devDependencies rather than dependending on globally installed packages. It's what I have done to lots of my projects. It takes up a more space when cloning and installing the packages, but it makes the handling easier.

Closes #30

### CODE REVIEW

**Comment by nknapp** [comment]
@msiegenthaler if you like, you can have a short look. If you are otherwise occupied, please let me know. I will then merge the changes tomorrow (if the tests pass)

**Comment by msiegenthaler** [comment]
Hi, I'm on vacation until next week without a computer so I can't really review it.

**Comment by nknapp** [comment]
OK, the question is how much you would like to make a review. Since you have done most of the work I feel that I should not release changes just like that.

However, I think, most of it is chore and you have already given your oppinion on the breaking changes in #30. The only other breaking change is that I have removed Node 7 from the Travis-Build and added Node 8 instead (i.e. Drop support for node 7).

I might just release it, if you are ok with it.

**Review by msiegenthaler — APPROVED** [review]
Looks good

**Comment by nknapp** [comment]
Thanks. I have release 1.0.0 now

**Pull request merged**
